import Employee from '../models/Employee.js';
import User from '../models/User.js';
import Project from '../models/Project.js';
import Customer from '../models/Customer.js';
import CalendarReminder from '../models/CalendarReminder.js';
import { createNotification, NotificationTemplates, sendToMultipleUsers } from './notificationController.js';
import { asyncHandler } from '../middleware/errorHandler.js';
import { autoGenerateAttendanceRecords, generateMissingAttendanceForEmployee, validateAndUpdateAttendance, deduplicateAttendance } from '../utils/attendanceService.js';

// @desc    Get all employees
// @route   GET /api/employees
// @access  Private
export const getEmployees = asyncHandler(async (req, res) => {
  const { search, designation, isActive = true, page = 1, limit = 10 } = req.query;

  let query = { isActive };

  if (search) {
    query.$or = [
      { name: { $regex: search, $options: 'i' } },
      { employeeId: { $regex: search, $options: 'i' } },
      { phone: { $regex: search, $options: 'i' } }
    ];
  }

  if (designation) query.designation = designation;

  const employees = await Employee.find(query)
    .populate('userId', 'name email role')
    .populate('createdBy', 'name')
    .sort({ createdAt: -1 })
    .limit(limit * 1)
    .skip((page - 1) * limit);

  const count = await Employee.countDocuments(query);

  res.json({
    success: true,
    data: employees,
    totalPages: Math.ceil(count / limit),
    currentPage: page,
    total: count
  });
});

// @desc    Get employees list for dropdowns (basic info only, accessible to all authenticated users)
// @route   GET /api/employees/list
// @access  Private (All authenticated users)
export const getEmployeesList = asyncHandler(async (req, res) => {
  const { search, limit = 10000 } = req.query;

  let query = { isActive: true };

  if (search) {
    query.$or = [
      { name: { $regex: search, $options: 'i' } },
      { employeeId: { $regex: search, $options: 'i' } }
    ];
  }

  const employees = await Employee.find(query)
    .select('_id name employeeId') // Only return essential fields
    .sort({ name: 1 })
    .limit(limit * 1);

  res.json({
    success: true,
    data: employees
  });
});

// @desc    Get single employee
// @route   GET /api/employees/:id
// @access  Private
export const getEmployee = asyncHandler(async (req, res) => {
  const employee = await Employee.findById(req.params.id)
    .populate('userId')
    .populate('assignedProjects.project')
    .populate('createdBy', 'name');

  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  res.json({
    success: true,
    data: employee
  });
});

// @desc    Create employee
// @route   POST /api/employees
// @access  Private
export const createEmployee = asyncHandler(async (req, res) => {
  const {
    name,
    phone,
    email,
    dateOfBirth,
    gender,
    address,
    designation,
    role,
    department,
    joiningDate,
    employmentType,
    basicSalary,
    allowances,
    deductions
  } = req.body;

  // Create user account for employee
  const user = await User.create({
    name,
    email,
    password: `emp${phone.slice(-4)}`, // Temporary password
    phone,
    role: 'employee',
    module: 'all',
    createdBy: req.user._id
  });

  // Normalize phone number (ensure it's 10 digits)
  let phoneNumber = phone || '0000000000';
  if (phoneNumber.length !== 10 || !/^\d+$/.test(phoneNumber)) {
    phoneNumber = '0000000000';
  }
  
  // Ensure designation and role are valid
  const validDesignations = ['supervisor', 'engineer', 'worker', 'technician', 'manager', 'helper', 'driver', 'admin', 'other'];
  const validRoles = ['supervisor', 'engineer', 'worker', 'technician', 'helper', 'driver', 'manager', 'admin'];
  
  const finalDesignation = validDesignations.includes(designation || role) ? (designation || role) : 'other';
  const finalRole = validRoles.includes(role || designation) ? (role || designation) : 'worker';
  
  // Ensure basicSalary is a number
  const finalBasicSalary = basicSalary !== undefined && basicSalary !== null ? Number(basicSalary) : 0;
  
  // Create employee (employeeId will be auto-generated by pre-validate hook)
  const employee = await Employee.create({
    userId: user._id,
    name,
    phone: phoneNumber,
    email,
    dateOfBirth,
    gender,
    address,
    designation: finalDesignation,
    role: finalRole,
    department: department || 'other',
    joiningDate: joiningDate || new Date(),
    employmentType: employmentType || 'full_time',
    basicSalary: finalBasicSalary,
    allowances: allowances || {
      hra: 0,
      transport: 0,
      other: 0
    },
    deductions: deductions || {
      pf: 0,
      esi: 0,
      tax: 0,
      other: 0
    },
    createdBy: req.user._id
  });

  res.status(201).json({
    success: true,
    data: employee,
    message: `Employee created. Temporary password: emp${phone.slice(-4)}`
  });
});

// @desc    Update employee
// @route   PUT /api/employees/:id
// @access  Private
export const updateEmployee = asyncHandler(async (req, res) => {
  let employee = await Employee.findById(req.params.id);

  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  employee = await Employee.findByIdAndUpdate(
    req.params.id,
    req.body,
    { new: true, runValidators: true }
  );

  res.json({
    success: true,
    data: employee
  });
});

// @desc    Delete employee
// @route   DELETE /api/employees/:id
// @access  Private
export const deleteEmployee = asyncHandler(async (req, res) => {
  const employee = await Employee.findById(req.params.id);

  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  employee.isActive = false;
  employee.exitDate = new Date();
  await employee.save();

  // Deactivate user account
  await User.findByIdAndUpdate(employee.userId, { isActive: false });

  res.json({
    success: true,
    message: 'Employee deactivated successfully'
  });
});

// @desc    Mark attendance
// @route   POST /api/employees/:id/attendance
// @access  Private
export const markAttendance = asyncHandler(async (req, res) => {
  const employee = await Employee.findById(req.params.id);

  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  const { date, status, checkInTime, checkOutTime, location, notes } = req.body;

  // Use the validation service to update or create attendance
  validateAndUpdateAttendance(employee, date, checkInTime, checkOutTime, location);
  
  // Add notes if provided (validateAndUpdateAttendance already found/created the record)
  if (notes) {
    // Find the attendance record that was just updated/created
    const normalizeDate = (d) => {
      const date = new Date(d);
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, '0');
      const day = String(date.getDate()).padStart(2, '0');
      return `${year}-${month}-${day}`;
    };
    
    const targetDateStr = normalizeDate(date);
    const attendanceRecord = employee.attendance.find(a => {
      const attDateStr = normalizeDate(a.date);
      return attDateStr === targetDateStr;
    });
    
    if (attendanceRecord) {
      attendanceRecord.notes = notes;
    }
  }

  await employee.save();

  res.json({
    success: true,
    data: employee,
    message: 'Attendance marked successfully'
  });
});

// @desc    Get attendance history
// @route   GET /api/employees/:id/attendance
// @access  Private
export const getAttendanceHistory = asyncHandler(async (req, res) => {
  const { startDate, endDate, month, year } = req.query;
  
  const employee = await Employee.findById(req.params.id);

  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  let attendance = employee.attendance;

  // Filter by month/year if provided
  if (month && year) {
    const targetMonth = parseInt(month);
    const targetYear = parseInt(year);
    
    attendance = attendance.filter(a => {
      const date = new Date(a.date);
      // JavaScript months are 0-indexed, so we need to add 1 for comparison
      return (date.getMonth() + 1) === targetMonth && date.getFullYear() === targetYear;
    });
  }
  // Filter by date range if provided
  else if (startDate && endDate) {
    attendance = attendance.filter(a => {
      const aDate = new Date(a.date);
      return aDate >= new Date(startDate) && aDate <= new Date(endDate);
    });
  }

  res.json({
    success: true,
    data: attendance.sort((a, b) => new Date(b.date) - new Date(a.date))
  });
});

// @desc    Admin edit attendance entry (check-in/out times and status)
// @route   PUT /api/employees/:id/attendance/:attendanceId
// @access  Private (Admin/with module)
export const updateAttendanceEntry = asyncHandler(async (req, res) => {
  const { id, attendanceId } = req.params;
  const { checkInTime, checkOutTime, status, notes } = req.body;
  const employee = await Employee.findById(id);
  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }
  const entry = employee.attendance.id(attendanceId);
  if (!entry) {
    return res.status(404).json({ message: 'Attendance entry not found' });
  }

  if (checkInTime) entry.checkInTime = new Date(checkInTime);
  if (checkOutTime) entry.checkOutTime = new Date(checkOutTime);
  if (typeof notes === 'string') entry.notes = notes;

  // Recompute work hours if both present
  if (entry.checkInTime && entry.checkOutTime) {
    const hours = (entry.checkOutTime - entry.checkInTime) / (1000 * 60 * 60);
    entry.workHours = Math.round(hours * 100) / 100;
    if (!status) {
      // Auto-determine unless explicit status provided
      if (entry.workHours >= 8.25) entry.status = 'present';
      else if (entry.workHours >= 4) entry.status = 'half_day';
      else entry.status = 'absent';
    }
  }
  if (status) entry.status = status;

  await employee.save();
  res.json({ success: true, data: entry, message: 'Attendance entry updated' });
});

// @desc    Auto-generate missing attendance records for all employees
// @route   POST /api/employees/attendance/auto-generate
// @access  Private (Admin only)
export const autoGenerateAllAttendance = asyncHandler(async (req, res) => {
  try {
    console.log('📋 Auto-generate attendance request received');
    
    // Set a timeout of 30 seconds
    const timeoutPromise = new Promise((_, reject) => {
      setTimeout(() => reject(new Error('Operation timed out after 30 seconds')), 30000);
    });
    
    // Race between the actual operation and timeout
    const result = await Promise.race([
      autoGenerateAttendanceRecords(),
      timeoutPromise
    ]);
    
    console.log('✅ Auto-generate completed:', result);
    
    if (result.success) {
      res.json({
        success: true,
        data: result,
        message: result.message || `Successfully generated ${result.created} attendance records for ${result.processed} employees (last 30 days)`
      });
    } else {
      res.status(500).json({
        success: false,
        message: result.error || 'Failed to generate attendance records'
      });
    }
  } catch (error) {
    console.error('❌ Auto-generate attendance error:', error);
    res.status(500).json({
      success: false,
      message: error.message || 'Failed to generate attendance records'
    });
  }
});

// @desc    Generate missing attendance for specific employee
// @route   POST /api/employees/:id/attendance/generate-missing
// @access  Private
export const generateMissingAttendance = asyncHandler(async (req, res) => {
  try {
    console.log(`📋 Generate missing attendance for employee: ${req.params.id}`);
    
    // Set a timeout of 30 seconds
    const timeoutPromise = new Promise((_, reject) => {
      setTimeout(() => reject(new Error('Operation timed out after 30 seconds')), 30000);
    });
    
    // Race between the actual operation and timeout
    const result = await Promise.race([
      generateMissingAttendanceForEmployee(req.params.id),
      timeoutPromise
    ]);
    
    console.log('✅ Generate missing completed:', result);
    
    res.json({
      success: true,
      data: result,
      message: result.message || `Generated ${result.created} attendance records`
    });
  } catch (error) {
    console.error('❌ Generate missing attendance error:', error);
    res.status(500).json({
      success: false,
      message: error.message || 'Failed to generate missing attendance'
    });
  }
});

// @desc    Deduplicate attendance records (remove duplicates for same date)
// @route   POST /api/employees/attendance/deduplicate
// @route   POST /api/employees/:id/attendance/deduplicate
// @access  Private
export const deduplicateAttendanceRecords = asyncHandler(async (req, res) => {
  try {
    console.log('📋 Deduplicate attendance request received');
    
    const employeeId = req.params.id || null;
    
    // Set a timeout of 60 seconds
    const timeoutPromise = new Promise((_, reject) => {
      setTimeout(() => reject(new Error('Operation timed out after 60 seconds')), 60000);
    });
    
    // Race between the actual operation and timeout
    const result = await Promise.race([
      deduplicateAttendance(employeeId),
      timeoutPromise
    ]);
    
    console.log('✅ Deduplication completed:', result);
    
    res.json({
      success: true,
      data: result,
      message: result.message || `Removed ${result.removed} duplicate attendance records`
    });
  } catch (error) {
    console.error('❌ Deduplication error:', error);
    res.status(500).json({
      success: false,
      message: error.message || 'Failed to deduplicate attendance records'
    });
  }
});

// @desc    Apply for leave
// @route   POST /api/employees/:id/leave
// @access  Private
export const applyLeave = asyncHandler(async (req, res) => {
  const employee = await Employee.findById(req.params.id);

  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  const { leaveType, startDate, endDate, reason } = req.body;
  
  // Calculate number of days
  const start = new Date(startDate);
  const end = new Date(endDate);
  const numberOfDays = Math.ceil((end - start) / (1000 * 60 * 60 * 24)) + 1;
  
  // If comp off, check balance
  if (leaveType === 'compoff') {
    const compOffBalance = employee.compOffBalance || 0;
    if (numberOfDays > compOffBalance) {
      return res.status(400).json({ 
        message: `Insufficient comp off balance. Available: ${compOffBalance} day(s), Requested: ${numberOfDays} day(s)` 
      });
    }
  }

  employee.leaves.push({
    leaveType,
    startDate,
    endDate,
    numberOfDays,
    reason,
    status: 'pending'
  });

  await employee.save();

  res.json({
    success: true,
    data: employee,
    message: 'Leave application submitted successfully'
  });
});

// @desc    Grant comp off to employee
// @route   POST /api/employees/:id/compoff/grant
// @access  Private (Admin)
export const grantCompOff = asyncHandler(async (req, res) => {
  const employee = await Employee.findById(req.params.id);
  
  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }
  
  const { days, reason, expiryDays } = req.body;
  
  if (!days || days <= 0) {
    return res.status(400).json({ message: 'Invalid number of days' });
  }
  
  // Calculate expiry date (default 90 days)
  const expiryDate = new Date();
  expiryDate.setDate(expiryDate.getDate() + (expiryDays || 90));
  
  // Add to comp off balance
  employee.compOffBalance = (employee.compOffBalance || 0) + days;
  
  // Add to history
  employee.compOffHistory.push({
    type: 'earned',
    days,
    date: new Date(),
    reason: reason || 'Comp off granted for working on holiday/overtime',
    grantedBy: req.user._id,
    expiryDate
  });
  
  await employee.save();
  
  // Notify employee
  if (employee.userId) {
    await createNotification({
      recipient: employee.userId,
      type: 'info',
      title: 'Comp Off Granted',
      message: `You have been granted ${days} day(s) of comp off. Balance: ${employee.compOffBalance} day(s)`,
      triggeredBy: req.user._id
    });
  }
  
  res.json({
    success: true,
    message: `${days} comp off day(s) granted successfully`,
    data: {
      newBalance: employee.compOffBalance,
      expiryDate
    }
  });
});

// @desc    Approve/Reject leave
// @route   PUT /api/employees/leave/:leaveId
// @access  Private
export const updateLeaveStatus = asyncHandler(async (req, res) => {
  const { status, reason } = req.body;

  const employee = await Employee.findOne({ 'leaves._id': req.params.leaveId });

  if (!employee) {
    return res.status(404).json({ message: 'Leave application not found' });
  }

  const leave = employee.leaves.id(req.params.leaveId);
  const previousStatus = leave.status;
  leave.status = status;
  leave.approvedBy = req.user._id;
  
  // If approving comp off leave, deduct from balance
  if (status === 'approved' && leave.leaveType === 'compoff' && previousStatus !== 'approved') {
    const compOffBalance = employee.compOffBalance || 0;
    employee.compOffBalance = Math.max(0, compOffBalance - (leave.numberOfDays || 0));
    
    // Add to comp off history
    employee.compOffHistory.push({
      type: 'used',
      days: leave.numberOfDays || 0,
      date: new Date(),
      reason: `Comp off used for leave from ${new Date(leave.startDate).toLocaleDateString()} to ${new Date(leave.endDate).toLocaleDateString()}`
    });
    
    console.log(`Deducted ${leave.numberOfDays} comp off days. New balance: ${employee.compOffBalance}`);
  }
  
  // If rejecting previously approved comp off, restore balance
  if (status === 'rejected' && leave.leaveType === 'compoff' && previousStatus === 'approved') {
    employee.compOffBalance = (employee.compOffBalance || 0) + (leave.numberOfDays || 0);
    console.log(`Restored ${leave.numberOfDays} comp off days. New balance: ${employee.compOffBalance}`);
  }

  await employee.save();

  // Notify employee about leave status
  if (employee.userId) {
    if (status === 'approved') {
      await createNotification({
        recipient: employee.userId,
        ...NotificationTemplates.leaveApproved(
          employee.name,
          new Date(leave.startDate).toLocaleDateString('en-IN'),
          new Date(leave.endDate).toLocaleDateString('en-IN'),
          req.user._id
        )
      });
    } else if (status === 'rejected') {
      await createNotification({
        recipient: employee.userId,
        ...NotificationTemplates.leaveRejected(reason, req.user._id)
      });
    }
  }

  res.json({
    success: true,
    data: employee,
    message: `Leave ${status} successfully`
  });
});

// @desc    Process salary
// @route   POST /api/employees/:id/salary
// @access  Private
export const processSalary = asyncHandler(async (req, res) => {
  const employee = await Employee.findById(req.params.id);

  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  const { month, paymentMode, notes } = req.body;

  // Check if salary already processed for the month
  const existingSalary = employee.salaryHistory.find(s => s.month === month);
  if (existingSalary) {
    return res.status(400).json({ message: 'Salary already processed for this month' });
  }

  const totalAllowances = Object.values(employee.allowances).reduce((sum, val) => sum + (val || 0), 0);
  const fixedDeductions = Object.values(employee.deductions).reduce((sum, val) => sum + (val || 0), 0);
  const grossSalary = employee.basicSalary + totalAllowances;

  // Calculate leave/attendance deductions for the target month
  const [y, m] = month.split('-').map(Number);
  const monthStart = new Date(y, (m - 1), 1);
  const monthEnd = new Date(y, (m - 1) + 1, 0, 23, 59, 59, 999);
  const attendanceThisMonth = (employee.attendance || []).filter(a => {
    const d = new Date(a.date);
    return d >= monthStart && d <= monthEnd;
  });

  // Approved leaves overlapping month
  let sickApprovedDays = 0;
  let otherApprovedLeaveDays = 0;
  (employee.leaves || []).forEach(l => {
    if (l.status === 'approved') {
      const s = new Date(l.startDate);
      const e = new Date(l.endDate);
      const from = s < monthStart ? monthStart : s;
      const to = e > monthEnd ? monthEnd : e;
      if (from <= to) {
        const days = Math.ceil((to - from) / (1000*60*60*24)) + 1;
        if (l.leaveType === 'sick') sickApprovedDays += days; else otherApprovedLeaveDays += days;
      }
    }
  });
  const halfDays = attendanceThisMonth.filter(a => a.status === 'half_day').length;
  const absents = attendanceThisMonth.filter(a => a.status === 'absent').length;
  // Daily rate approximation of 26 working days
  const dailyRate = (employee.basicSalary + totalAllowances - fixedDeductions) / 26;
  const unpaidSickDays = Math.max(0, sickApprovedDays - 1);
  const leaveDeductions = Math.max(0, Math.round(((unpaidSickDays + otherApprovedLeaveDays + absents) * dailyRate + halfDays * (dailyRate/2)) * 100) / 100);

  // Hold (Retention) 5% by default
  const holdPercent = employee.holdPercent || 5;
  const prelimNet = grossSalary - fixedDeductions - leaveDeductions;
  const holdAmount = Math.max(0, Math.round((prelimNet * holdPercent / 100) * 100) / 100);
  const payableNet = Math.max(0, Math.round((prelimNet - holdAmount) * 100) / 100);

  employee.salaryHistory.push({
    month,
    basicSalary: employee.basicSalary,
    totalAllowances,
    totalDeductions: fixedDeductions + leaveDeductions + holdAmount,
    netSalary: payableNet,
    paidDate: new Date(),
    paymentMode,
    status: 'paid',
    notes
  });

  // Update hold balance accumulator
  employee.holdBalance = (employee.holdBalance || 0) + holdAmount;

  await employee.save();

  // Notify employee about salary processed
  if (employee.userId) {
    await createNotification({
      recipient: employee.userId,
      ...NotificationTemplates.salaryProcessed(month, payableNet.toFixed(2)),
      triggeredBy: req.user._id
    });
  }

  res.json({
    success: true,
    data: employee,
    message: 'Salary processed successfully',
    salaryDetails: {
      month,
      grossSalary,
      fixedDeductions,
      leaveDeductions,
      holdPercent,
      holdAmount,
      payableNet
    }
  });
});

// @desc    Preview salary calculation for a month (no save)
// @route   GET /api/employees/:id/salary-preview?month=YYYY-MM
// @access  Private
export const getSalaryPreview = asyncHandler(async (req, res) => {
  const employee = await Employee.findById(req.params.id);
  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }
  const { month } = req.query;
  if (!month) {
    return res.status(400).json({ message: 'Month (YYYY-MM) is required' });
  }

  const totalAllowances = Object.values(employee.allowances).reduce((sum, val) => sum + (val || 0), 0);
  const fixedDeductions = Object.values(employee.deductions).reduce((sum, val) => sum + (val || 0), 0);
  const grossSalary = employee.basicSalary + totalAllowances;

  const [y, m] = month.split('-').map(Number);
  const monthStart = new Date(y, (m - 1), 1);
  const monthEnd = new Date(y, (m - 1) + 1, 0, 23, 59, 59, 999);

  const attendanceThisMonth = (employee.attendance || []).filter(a => {
    const d = new Date(a.date);
    return d >= monthStart && d <= monthEnd;
  });

  let sickApprovedDays = 0;
  let otherApprovedLeaveDays = 0;
  (employee.leaves || []).forEach(l => {
    if (l.status === 'approved') {
      const s = new Date(l.startDate);
      const e = new Date(l.endDate);
      const from = s < monthStart ? monthStart : s;
      const to = e > monthEnd ? monthEnd : e;
      if (from <= to) {
        const days = Math.ceil((to - from) / (1000*60*60*24)) + 1;
        if (l.leaveType === 'sick') sickApprovedDays += days; else otherApprovedLeaveDays += days;
      }
    }
  });

  const halfDays = attendanceThisMonth.filter(a => a.status === 'half_day').length;
  const absents = attendanceThisMonth.filter(a => a.status === 'absent').length;
  const dailyRate = (employee.basicSalary + totalAllowances - fixedDeductions) / 26;
  const unpaidSickDays = Math.max(0, sickApprovedDays - 1);
  const leaveDeductions = Math.max(0, Math.round(((unpaidSickDays + otherApprovedLeaveDays + absents) * dailyRate + halfDays * (dailyRate/2)) * 100) / 100);

  const holdPercent = employee.holdPercent || 5;
  const prelimNet = grossSalary - fixedDeductions - leaveDeductions;
  const holdAmount = Math.max(0, Math.round((prelimNet * holdPercent / 100) * 100) / 100);
  const payableNet = Math.max(0, Math.round((prelimNet - holdAmount) * 100) / 100);

  res.json({
    success: true,
    data: {
      month,
      grossSalary,
      totalAllowances,
      fixedDeductions,
      leaveDeductions,
      holdPercent,
      holdAmount,
      payableNet
    }
  });
});

// @desc    Get salary history
// @route   GET /api/employees/:id/salary-history
// @access  Private
export const getSalaryHistory = asyncHandler(async (req, res) => {
  const employee = await Employee.findById(req.params.id);

  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  res.json({
    success: true,
    data: employee.salaryHistory.sort((a, b) => new Date(b.paidDate) - new Date(a.paidDate))
  });
});

// @desc    Generate payslip PDF
// @route   GET /api/employees/:id/salary/:salaryId/payslip
// @access  Private
export const generatePayslip = asyncHandler(async (req, res) => {
  const { id, salaryId } = req.params;
  
  const employee = await Employee.findById(id);
  
  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }
  
  // Find the specific salary record
  const salaryRecord = employee.salaryHistory.find(s => s._id.toString() === salaryId);
  
  if (!salaryRecord) {
    return res.status(404).json({ message: 'Salary record not found' });
  }
  
  // Get company details from settings
  const Settings = (await import('../models/Settings.js')).default;
  const settings = await Settings.findOne();
  
  const companyDetails = {
    name: settings?.companyName || 'Sanjana Enterprises',
    address: settings?.companyAddress || '',
    phone: settings?.companyPhone || '',
    email: settings?.companyEmail || ''
  };
  
  // Prepare salary data for payslip
  const salaryData = {
    month: salaryRecord.month,
    paymentDate: salaryRecord.paidDate,
    paymentMode: salaryRecord.paymentMode || 'Bank Transfer',
    workingDays: salaryRecord.presentDays || 0,
    basicSalary: salaryRecord.basicSalary || employee.basicSalary || 0,
    hra: employee.allowances?.hra || 0,
    conveyance: employee.allowances?.conveyance || 0,
    medical: employee.allowances?.medical || 0,
    otherAllowances: employee.allowances?.other || 0,
    pf: employee.deductions?.pf || 0,
    esi: employee.deductions?.esi || 0,
    professionalTax: employee.deductions?.professionalTax || 0,
    tds: employee.deductions?.tds || 0,
    otherDeductions: salaryRecord.otherDeductions || 0,
    advance: salaryRecord.advanceDeduction || 0
  };
  
  // Generate PDF
  const generatePayslipPDF = (await import('../utils/payslipService.js')).default;
  const pdfBuffer = await generatePayslipPDF(salaryData, employee, companyDetails);
  
  // Set response headers
  const filename = `Payslip_${employee.employeeId}_${salaryRecord.month.replace('-', '_')}.pdf`;
  
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.setHeader('Content-Length', pdfBuffer.length);
  
  res.send(pdfBuffer);
});

// @desc    Add work update
// @route   POST /api/employees/:id/work-update
// @access  Private
export const addWorkUpdate = asyncHandler(async (req, res) => {
  const employee = await Employee.findById(req.params.id);

  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  const { project, description, images } = req.body;

  employee.workUpdates.push({
    project,
    description,
    images,
    submittedBy: req.user._id
  });

  await employee.save();

  res.json({
    success: true,
    data: employee,
    message: 'Work update added successfully'
  });
});

// @desc    Get work updates
// @route   GET /api/employees/:id/work-updates
// @access  Private
export const getWorkUpdates = asyncHandler(async (req, res) => {
  const employee = await Employee.findById(req.params.id)
    .populate('workUpdates.project', 'projectId name description')
    .populate('workUpdates.submittedBy', 'name');

  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  res.json({
    success: true,
    data: employee.workUpdates.sort((a, b) => new Date(b.date) - new Date(a.date))
  });
});

// @desc    Update employee role
// @route   PUT /api/employees/:id/role
// @access  Private
export const updateEmployeeRole = asyncHandler(async (req, res) => {
  const { role, reportingTo } = req.body;

  const employee = await Employee.findById(req.params.id);
  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  employee.role = role;
  employee.designation = role;
  if (reportingTo) {
    employee.reportingTo = reportingTo;
  }

  await employee.save();

  const populated = await Employee.findById(employee._id)
    .populate('reportingTo', 'name employeeId role');

  res.json({
    success: true,
    data: populated,
    message: `Role updated to ${role} successfully`
  });
});

// @desc    Assign project to employee
// @route   POST /api/employees/:id/assign-project
// @access  Private
export const assignProjectToEmployee = asyncHandler(async (req, res) => {
  const { projectId, role } = req.body; // role: supervisor, engineer, worker, helper

  console.log('Assigning project to employee:', { employeeId: req.params.id, projectId, role });

  const employee = await Employee.findById(req.params.id);
  if (!employee) {
    console.log('Employee not found:', req.params.id);
    return res.status(404).json({ message: 'Employee not found' });
  }

  const project = await Project.findById(projectId);
  if (!project) {
    console.log('Project not found:', projectId);
    return res.status(404).json({ message: 'Project not found' });
  }

  // Check if already assigned
  const existing = employee.assignedProjects.find(
    ap => ap.project.toString() === projectId && ap.status === 'active'
  );

  if (existing) {
    console.log('Project already assigned to employee:', { projectId, employeeId: employee._id });
    return res.status(400).json({ message: 'Already assigned to this project' });
  }

  // Add to employee's assigned projects
  const assignment = {
    project: projectId,
    role: role || employee.role,
    assignedBy: req.user._id,
    status: 'active'
  };
  
  employee.assignedProjects.push(assignment);
  console.log('Added project to employee assignedProjects:', assignment);

  // If supervisor, add to managed projects
  if (role === 'supervisor' || employee.role === 'supervisor') {
    if (!employee.managedProjects.includes(projectId)) {
      employee.managedProjects.push(projectId);
      console.log('Added project to employee managedProjects:', projectId);
    }
  }

  await employee.save();
  console.log('Employee saved with assigned project');

  // Update project with employee assignment
  project.assignEmployee(employee._id, role || employee.role, req.user._id);
  await project.save();
  console.log('Project updated with employee assignment');

  const populated = await Employee.findById(employee._id)
    .populate('assignedProjects.project', 'projectId name description status');

  console.log('Populated employee data:', JSON.stringify(populated.assignedProjects, null, 2));

  res.json({
    success: true,
    data: populated,
    message: `Project assigned successfully as ${role || employee.role}`
  });
});

// @desc    Get employee's assigned projects
// @route   GET /api/employees/:id/projects
// @access  Private
export const getEmployeeProjects = asyncHandler(async (req, res) => {
  const employee = await Employee.findById(req.params.id)
    .populate('assignedProjects.project', 'projectId name description status customer category')
    .populate('assignedProjects.assignedBy', 'name');

  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  const activeProjects = employee.assignedProjects.filter(ap => ap.status === 'active');

  res.json({
    success: true,
    data: {
      activeProjects,
      allProjects: employee.assignedProjects
    }
  });
});

// @desc    Get employees by role
// @route   GET /api/employees/by-role/:role
// @access  Private
export const getEmployeesByRole = asyncHandler(async (req, res) => {
  const { role } = req.params;

  const employees = await Employee.find({ 
    role,
    isActive: true 
  })
    .populate('reportingTo', 'name employeeId')
    .select('employeeId name phone role designation assignedProjects')
    .sort({ name: 1 });

  res.json({
    success: true,
    data: employees
  });
});

// @desc    Get supervisor's team members
// @route   GET /api/employees/:id/team
// @access  Private
export const getSupervisorTeam = asyncHandler(async (req, res) => {
  const supervisor = await Employee.findById(req.params.id);
  
  if (!supervisor) {
    return res.status(404).json({ message: 'Supervisor not found' });
  }

  // Get all employees reporting to this supervisor
  const team = await Employee.find({ 
    reportingTo: req.params.id,
    isActive: true 
  })
    .populate('assignedProjects.project', 'projectId name description status')
    .select('employeeId name phone role designation assignedProjects');

  res.json({
    success: true,
    data: {
      supervisor: {
        _id: supervisor._id,
        name: supervisor.name,
        employeeId: supervisor.employeeId,
        role: supervisor.role
      },
      team
    }
  });
});

// ============= EMPLOYEE SELF-SERVICE FUNCTIONS =============

// @desc    Mark attendance with GPS location
// @route   POST /api/employees/my-attendance
// @access  Private (Employee)
export const markMyAttendance = asyncHandler(async (req, res) => {
  const { type, location, notes } = req.body; // type: 'checkin' or 'checkout'
  
  // Find employee by userId
  const employee = await Employee.findOne({ userId: req.user._id });
  if (!employee) {
    return res.status(404).json({ message: 'Employee record not found' });
  }

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  // Find or create today's attendance
  let attendance = employee.attendance.find(
    a => new Date(a.date).setHours(0, 0, 0, 0) === today.getTime()
  );

  if (type === 'checkin') {
    if (attendance && attendance.checkInTime) {
      return res.status(400).json({ message: 'Already checked in today' });
    }

    if (!attendance) {
      attendance = {
        date: new Date(),
        checkInTime: new Date(),
        checkInLocation: {
          type: 'Point',
          coordinates: location?.coordinates || [0, 0],
          address: location?.address || 'Location not provided'
        },
        status: 'present',
        markedBy: req.user._id,
        notes: notes || ''
      };
      employee.attendance.push(attendance);
    } else {
      attendance.checkInTime = new Date();
      attendance.checkInLocation = {
        type: 'Point',
        coordinates: location?.coordinates || [0, 0],
        address: location?.address || 'Location not provided'
      };
      attendance.status = 'present';
      attendance.markedBy = req.user._id;
    }
  } else if (type === 'checkout') {
    if (!attendance || !attendance.checkInTime) {
      return res.status(400).json({ message: 'Please check in first' });
    }
    if (attendance.checkOutTime) {
      return res.status(400).json({ message: 'Already checked out today' });
    }

    attendance.checkOutTime = new Date();
    attendance.checkOutLocation = {
      type: 'Point',
      coordinates: location?.coordinates || [0, 0],
      address: location?.address || 'Location not provided'
    };
    
    // Calculate work hours
    const hours = (attendance.checkOutTime - attendance.checkInTime) / (1000 * 60 * 60);
    attendance.workHours = Math.round(hours * 100) / 100;
    
    // Automatically determine attendance status based on work hours
    if (attendance.workHours >= 8.25) { // 8 hours 15 minutes
      attendance.status = 'present';
    } else if (attendance.workHours >= 4) { // 4 hours
      attendance.status = 'half_day';
    } else {
      attendance.status = 'absent';
    }
  }

  await employee.save();

  res.json({
    success: true,
    data: attendance,
    message: type === 'checkin' ? 'Checked in successfully' : 'Checked out successfully'
  });
});

// @desc    Get my attendance history
// @route   GET /api/employees/my-attendance
// @access  Private (Employee)
export const getMyAttendance = asyncHandler(async (req, res) => {
  const { month, year } = req.query;
  
  const employee = await Employee.findOne({ userId: req.user._id });
  if (!employee) {
    return res.status(404).json({ message: 'Employee record not found' });
  }

  let attendance = employee.attendance;

  // Filter by month/year if provided
  if (month && year) {
    const targetMonth = parseInt(month);
    const targetYear = parseInt(year);
    
    attendance = attendance.filter(a => {
      const date = new Date(a.date);
      // JavaScript months are 0-indexed, so we need to add 1 for comparison
      return (date.getMonth() + 1) === targetMonth && date.getFullYear() === targetYear;
    });
  }

  res.json({
    success: true,
    data: attendance.sort((a, b) => b.date - a.date)
  });
});

// @desc    Get my salary history
// @route   GET /api/employees/my-salary
// @access  Private (Employee)
export const getMySalary = asyncHandler(async (req, res) => {
  const employee = await Employee.findOne({ userId: req.user._id });
  if (!employee) {
    return res.status(404).json({ message: 'Employee record not found' });
  }

  // Format current month as YYYY-MM
  const now = new Date();
  const currentMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  
  // Find if salary has been processed for current month
  const currentSalaryRecord = employee.salaryHistory.find(s => s.month === currentMonth);

  // Calculate current month salary based on employee's allowances and deductions
  const totalAllowances = Object.values(employee.allowances).reduce((sum, val) => sum + (val || 0), 0);
  const totalDeductions = Object.values(employee.deductions).reduce((sum, val) => sum + (val || 0), 0);
  const netSalary = employee.basicSalary + totalAllowances - totalDeductions;

  // Leave/attendance deduction calculation for current month
  const monthStart = new Date(now.getFullYear(), now.getMonth(), 1);
  const monthEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0, 23, 59, 59, 999);
  const attendanceThisMonth = (employee.attendance || []).filter(a => {
    const d = new Date(a.date);
    return d >= monthStart && d <= monthEnd;
  });
  const dailyRate = netSalary / 26; // working days approx
  let sickApprovedDays = 0;
  let otherApprovedLeaveDays = 0;
  // Approved leaves overlapping current month
  (employee.leaves || []).forEach(l => {
    if (l.status === 'approved') {
      const s = new Date(l.startDate);
      const e = new Date(l.endDate);
      const from = s < monthStart ? monthStart : s;
      const to = e > monthEnd ? monthEnd : e;
      if (from <= to) {
        const days = Math.ceil((to - from) / (1000*60*60*24)) + 1;
        if (l.leaveType === 'sick') sickApprovedDays += days; else otherApprovedLeaveDays += days;
      }
    }
  });
  // First 1 sick day is paid
  const unpaidSickDays = Math.max(0, sickApprovedDays - 1);
  // Half-day and absent from attendance
  const halfDays = attendanceThisMonth.filter(a => a.status === 'half_day').length;
  const absents = attendanceThisMonth.filter(a => a.status === 'absent').length;
  const leaveDeductions = Math.round(((unpaidSickDays + otherApprovedLeaveDays + absents) * dailyRate + halfDays * (dailyRate/2)) * 100) / 100;

  // Format current month data for frontend
  const currentMonthData = currentSalaryRecord 
    ? {
        month: currentSalaryRecord.month,
        status: currentSalaryRecord.status,
        netAmount: currentSalaryRecord.netSalary,
        grossAmount: currentSalaryRecord.basicSalary + currentSalaryRecord.totalAllowances,
        deductions: currentSalaryRecord.totalDeductions,
        paymentDate: currentSalaryRecord.paidDate
      }
    : {
        month: currentMonth,
        status: 'pending',
        netAmount: Math.max(0, netSalary - leaveDeductions),
        grossAmount: employee.basicSalary + totalAllowances,
        deductions: totalDeductions + leaveDeductions,
        paymentDate: null
      };

  // Format salary history for frontend
  const formattedHistory = employee.salaryHistory.map(record => ({
    month: record.month,
    grossAmount: record.basicSalary + record.totalAllowances,
    deductions: record.totalDeductions,
    netAmount: record.netSalary,
    status: record.status,
    paymentDate: record.paidDate,
    paymentMode: record.paymentMode,
    notes: record.notes
  })).sort((a, b) => b.month.localeCompare(a.month));

  res.json({
    success: true,
    data: {
      basicSalary: employee.basicSalary,
      allowances: employee.allowances,
      deductions: employee.deductions,
      totalAllowances,
      totalDeductions,
      netSalary,
      leaveDeductions,
      currentMonth: currentMonthData,
      history: formattedHistory
    }
  });
});

// ============= HOLD (RETENTION) ==================
// @desc    Get my hold (retention) summary
// @route   GET /api/employees/my-hold
// @access  Private (Employee)
export const getMyHold = asyncHandler(async (req, res) => {
  const employee = await Employee.findOne({ userId: req.user._id });
  if (!employee) {
    return res.status(404).json({ message: 'Employee record not found' });
  }

  // Calculate employment tenure in months
  const joiningDate = new Date(employee.joiningDate);
  const today = new Date();
  const tenureMonths = Math.floor((today - joiningDate) / (1000 * 60 * 60 * 24 * 30.44));
  const canWithdraw = tenureMonths >= 6;

  const holdPercent = employee.holdPercent || 5;
  // Calculate accrual from paid salary history (for display)
  let totalAccrued = 0;
  (employee.salaryHistory || []).forEach(r => {
    if (r.status === 'paid') {
      const hold = Math.round((r.netSalary * holdPercent / 100) * 100) / 100;
      totalAccrued += hold;
    }
  });

  const approvedRequests = (employee.holdRequests || []).filter(r => r.status === 'approved');
  const withdrawn = approvedRequests.reduce((s, r) => s + (r.amount || 0), 0);
  const pending = (employee.holdRequests || []).filter(r => r.status === 'pending').reduce((s, r) => s + (r.amount || 0), 0);

  // Use stored holdBalance as current available balance tracker
  const holdBalance = Math.max(0, (employee.holdBalance || 0));
  
  // Calculate withdrawable amount based on tenure
  let withdrawable = 0;
  if (canWithdraw) {
    // After 6 months: 3 months worth is releasable
    const avgHoldPerMonth = totalAccrued / Math.max(1, employee.salaryHistory.length);
    const releasableAmount = avgHoldPerMonth * 3;
    withdrawable = Math.max(0, Math.min(releasableAmount, holdBalance) - pending);
  }

  res.json({
    success: true,
    data: {
      holdPercent,
      totalAccrued: Math.round(totalAccrued * 100) / 100,
      holdBalance: Math.round(holdBalance * 100) / 100,
      withdrawable: Math.round(withdrawable * 100) / 100,
      pendingRequestsAmount: Math.round(pending * 100) / 100,
      tenureMonths,
      canWithdraw,
      monthsUntilEligible: canWithdraw ? 0 : 6 - tenureMonths,
      joiningDate: employee.joiningDate
    }
  });
});

// @desc    Request hold withdrawal
// @route   POST /api/employees/my-hold/request
// @access  Private (Employee)
export const requestMyHoldWithdrawal = asyncHandler(async (req, res) => {
  const { amount, notes } = req.body;
  const employee = await Employee.findOne({ userId: req.user._id });
  if (!employee) {
    return res.status(404).json({ message: 'Employee record not found' });
  }

  // Calculate employment tenure in months
  const joiningDate = new Date(employee.joiningDate);
  const today = new Date();
  const tenureMonths = Math.floor((today - joiningDate) / (1000 * 60 * 60 * 24 * 30.44)); // Average month
  
  console.log(`Employee tenure: ${tenureMonths} months`);

  // Withdrawal policy: After 6 months, release 3 months worth, hold 3 months
  if (tenureMonths < 6) {
    return res.status(400).json({ 
      message: `Cannot withdraw hold amount before 6 months of employment. Current tenure: ${tenureMonths} months` 
    });
  }

  // Calculate total hold accumulated (from salary history)
  const totalHoldAccumulated = employee.salaryHistory.reduce((sum, s) => sum + (s.holdAmount || 0), 0);
  
  // After 6 months: 3 months worth is releasable, 3 months worth stays held
  // Assuming roughly equal hold per month
  const avgHoldPerMonth = totalHoldAccumulated / employee.salaryHistory.length || 0;
  const releasableAmount = avgHoldPerMonth * 3; // 3 months worth
  const mustStayHeld = avgHoldPerMonth * 3; // 3 months worth must stay held
  
  // Subtract pending requests
  const pending = (employee.holdRequests || []).filter(r => r.status === 'pending').reduce((s, r) => s + (r.amount || 0), 0);
  const withdrawable = Math.max(0, releasableAmount - pending);

  console.log(`Total hold: ₹${totalHoldAccumulated}, Releasable: ₹${releasableAmount}, Must stay held: ₹${mustStayHeld}, Withdrawable: ₹${withdrawable}`);

  if (!amount || amount <= 0) {
    return res.status(400).json({ message: 'Invalid amount' });
  }
  
  if (amount > withdrawable) {
    return res.status(400).json({ 
      message: `Requested amount exceeds withdrawable balance. You can withdraw up to ₹${withdrawable.toFixed(2)} (3 months worth). Remaining ₹${mustStayHeld.toFixed(2)} must stay held.` 
    });
  }

  employee.holdRequests.push({ 
    amount, 
    status: 'pending', 
    requestedAt: new Date(), 
    notes: notes || '' 
  });
  await employee.save();

  res.status(201).json({ 
    success: true, 
    message: `Withdrawal request submitted for ₹${amount}. After 6 months, you can withdraw 3 months worth (₹${releasableAmount.toFixed(2)}).`,
    data: {
      requestedAmount: amount,
      releasableAmount,
      mustStayHeld,
      withdrawable
    }
  });
});

// @desc    Get my employee profile
// @route   GET /api/employees/my-profile
// @access  Private (Employee)
export const getMyProfile = asyncHandler(async (req, res) => {
  const employee = await Employee.findOne({ userId: req.user._id })
    .populate('userId', 'name email role')
    .populate('reportingTo', 'name employeeId');

  if (!employee) {
    return res.status(404).json({ message: 'Employee record not found' });
  }

  res.json({
    success: true,
    data: employee
  });
});

// @desc    Get my assigned projects
// @route   GET /api/employees/my-projects
// @access  Private (Employee)
export const getMyProjects = asyncHandler(async (req, res) => {
  console.log('Fetching projects for user:', req.user._id);
  
  // First, let's try to find any employee record with this userId
  const anyEmployee = await Employee.findOne({ userId: req.user._id });
  console.log('Any employee with this userId:', anyEmployee ? anyEmployee._id : 'None found');
  
  const employee = await Employee.findOne({ userId: req.user._id })
    .populate('assignedProjects.project', 'projectId name description status category customer startDate expectedEndDate')
    .populate('assignedProjects.assignedBy', 'name');

  if (!employee) {
    console.log('Employee not found for userId:', req.user._id);
    // Let's also check all employees to see if we can find a match
    const allEmployees = await Employee.find({}, 'userId name employeeId');
    console.log('All employees:', allEmployees.map(e => ({ id: e._id, userId: e.userId, name: e.name, employeeId: e.employeeId })));
    return res.status(404).json({ message: 'Employee record not found' });
  }

  console.log('Employee found:', employee._id);
  console.log('Employee userId:', employee.userId);
  console.log('Employee assignedProjects length:', employee.assignedProjects.length);
  console.log('Employee assignedProjects:', JSON.stringify(employee.assignedProjects, null, 2));

  const activeProjects = employee.assignedProjects.filter(ap => ap.status === 'active');
  
  console.log('Active projects count:', activeProjects.length);
  console.log('Active projects:', JSON.stringify(activeProjects, null, 2));

  res.json({
    success: true,
    data: {
      activeProjects,
      totalProjects: employee.assignedProjects.length
    }
  });
});

// @desc    Get my leads (customers where I am the leadFrom or followUpPerson)
// @route   GET /api/employees/my-leads
// @access  Private (Employee)
export const getMyLeads = asyncHandler(async (req, res) => {
  const { search, leadStatus, leadType, page = 1, limit = 10 } = req.query;

  // Find employee record for the logged-in user
  const employee = await Employee.findOne({ userId: req.user._id });

  if (!employee) {
    return res.status(404).json({ message: 'Employee record not found' });
  }

  // Build query based on leadType filter
  let query = {};
  
  if (leadType === 'my_leads') {
    // Only leads where I am the leadFrom
    query.leadFrom = employee._id;
  } else if (leadType === 'follow_up') {
    // Only leads where I am the followUpPerson
    query.followUpPerson = employee._id;
  } else {
    // All leads where I am either leadFrom OR followUpPerson
    query.$or = [
      { leadFrom: employee._id },
      { followUpPerson: employee._id }
    ];
  }

  if (search) {
    query.$or = [
      { name: { $regex: search, $options: 'i' } },
      { contactNumber: { $regex: search, $options: 'i' } },
      { email: { $regex: search, $options: 'i' } }
    ];
  }

  if (leadStatus) {
    query.leadStatus = leadStatus;
  }

  // Execute query with pagination
  const customers = await Customer.find(query)
    .populate('assignedTo', 'name email')
    .populate('leadFrom', 'name employeeId')
    .populate('followUpPerson', 'name employeeId')
    .populate('createdBy', 'name')
    .sort({ createdAt: -1 })
    .limit(limit * 1)
    .skip((page - 1) * limit);

  const count = await Customer.countDocuments(query);

  res.json({
    success: true,
    data: customers,
    totalPages: Math.ceil(count / limit),
    currentPage: page,
    total: count
  });
});

// @desc    Create my lead (customer with leadFrom set to current employee)
// @route   POST /api/employees/my-leads
// @access  Private (Employee)
export const createMyLead = asyncHandler(async (req, res) => {
  // Find employee record for the logged-in user
  const employee = await Employee.findOne({ userId: req.user._id });

  if (!employee) {
    return res.status(404).json({ message: 'Employee record not found' });
  }

  const {
    name,
    contactNumber,
    alternateContact,
    email,
    address,
    callType,
    dataSource,
    leadStatus,
    leadDate,
    followUpPerson,
    notes,
    tags
  } = req.body;

  // Check if customer with same contact number exists
  const customerExists = await Customer.findOne({ contactNumber });
  if (customerExists) {
    return res.status(400).json({ message: 'Customer with this contact number already exists' });
  }

  // Clean up empty strings for ObjectId fields
  const cleanFollowUpPerson = followUpPerson && followUpPerson.trim() !== '' ? followUpPerson : undefined;

  // Create customer with leadFrom automatically set to current employee
  const customer = await Customer.create({
    name,
    contactNumber,
    alternateContact,
    email,
    address,
    callType,
    dataSource,
    leadStatus: leadStatus || 'new',
    leadFrom: employee._id, // Automatically set to current employee
    leadDate: leadDate ? new Date(leadDate) : new Date(),
    followUpPerson: cleanFollowUpPerson,
    notes,
    tags: tags ? (Array.isArray(tags) ? tags : tags.split(',').map(t => t.trim()).filter(t => t)) : [],
    createdBy: req.user._id
  });

  // Populate fields for response
  await customer.populate('leadFrom', 'name employeeId');
  await customer.populate('followUpPerson', 'name employeeId');

  res.status(201).json({
    success: true,
    data: customer,
    message: 'Lead created successfully'
  });
});

// @desc    Update my lead (only if leadFrom matches current employee)
// @route   PUT /api/employees/my-leads/:id
// @access  Private (Employee)
export const updateMyLead = asyncHandler(async (req, res) => {
  // Find employee record for the logged-in user
  const employee = await Employee.findOne({ userId: req.user._id });

  if (!employee) {
    return res.status(404).json({ message: 'Employee record not found' });
  }

  const customer = await Customer.findById(req.params.id);

  if (!customer) {
    return res.status(404).json({ message: 'Customer not found' });
  }

  // Verify that this lead belongs to the current employee
  if (customer.leadFrom?.toString() !== employee._id.toString()) {
    return res.status(403).json({ message: 'You can only update your own leads' });
  }

  // Update customer
  const updatedCustomer = await Customer.findByIdAndUpdate(
    req.params.id,
    req.body,
    { new: true, runValidators: true }
  )
    .populate('leadFrom', 'name employeeId')
    .populate('followUpPerson', 'name employeeId')
    .populate('assignedTo', 'name email')
    .populate('createdBy', 'name');

  res.json({
    success: true,
    data: updatedCustomer,
    message: 'Lead updated successfully'
  });
});

// @desc    Submit work update
// @route   POST /api/employees/work-update
// @access  Private (Employee)
export const submitMyWorkUpdate = asyncHandler(async (req, res) => {
  const { projectId, description, images, audioNotes, videoRecordings } = req.body;
  
  const employee = await Employee.findOne({ userId: req.user._id });
  if (!employee) {
    return res.status(404).json({ message: 'Employee record not found' });
  }

  // Parse arrays from body (they may come as strings from FormData)
  let uploadedImages = Array.isArray(images) ? images : (images ? [images] : []);
  let uploadedAudioNotes = Array.isArray(audioNotes) ? audioNotes : (audioNotes ? [audioNotes] : []);
  let uploadedVideoRecordings = Array.isArray(videoRecordings) ? videoRecordings : (videoRecordings ? [videoRecordings] : []);

  // If files are uploaded with this request, upload them to S3
  if (req.files && req.files.length > 0) {
    try {
      const { uploadMultipleFromMemory } = await import('../utils/s3Service.js');
      const uploadedFiles = await uploadMultipleFromMemory(req.files, 'work-updates');

      // Categorize uploaded files based on their type
      uploadedFiles.forEach((file, index) => {
        const originalFile = req.files[index];
        const fileUrl = file.url;
        
        if (originalFile.mimetype.startsWith('image/')) {
          uploadedImages.push(fileUrl);
        } else if (originalFile.mimetype.startsWith('audio/')) {
          uploadedAudioNotes.push(fileUrl);
        } else if (originalFile.mimetype.startsWith('video/')) {
          uploadedVideoRecordings.push(fileUrl);
        }
      });
    } catch (error) {
      console.error('S3 upload error:', error);
      return res.status(500).json({ 
        success: false, 
        message: 'Failed to upload files to S3',
        error: error.message 
      });
    }
  }

  console.log('Work update data:', { projectId, description, uploadedImages, uploadedAudioNotes, uploadedVideoRecordings });

  employee.workUpdates.push({
    date: new Date(),
    project: projectId,
    description,
    images: uploadedImages,
    audioNotes: uploadedAudioNotes,
    videoRecordings: uploadedVideoRecordings,
    submittedBy: req.user._id
  });

  await employee.save();

  // Also add to project history
  if (projectId) {
    const project = await Project.findById(projectId);
    if (project) {
      project.addWorkUpdate({
        title: `Update by ${employee.name}`,
        description,
        status: 'in_progress',
        images: uploadedImages,
        audioNotes: uploadedAudioNotes,
        videoRecordings: uploadedVideoRecordings,
        updatedBy: employee._id
      });
      await project.save();
      
      // Notify project supervisors and admin about work update
      const supervisorIds = project.supervisors
        .map(s => s.employee)
        .filter(id => id.toString() !== employee._id.toString());
      
      if (supervisorIds.length > 0) {
        const supervisors = await Employee.find({ _id: { $in: supervisorIds } }).select('userId');
        const userIds = supervisors.map(s => s.userId).filter(Boolean);
        
        if (userIds.length > 0) {
          await sendToMultipleUsers(userIds, NotificationTemplates.workUpdateSubmitted(
            employee.name,
            project.description || project.projectId,
            project._id,
            req.user._id
          ));
        }
      }
    }
  }

  res.json({
    success: true,
    message: 'Work update submitted successfully',
    data: {
      images: uploadedImages,
      audioNotes: uploadedAudioNotes,
      videoRecordings: uploadedVideoRecordings
    }
  });
});

// @desc    Upload work update files
// @route   POST /api/employees/upload-work-files
// @access  Private (Employee)
export const uploadWorkUpdateFiles = asyncHandler(async (req, res) => {
  if (!req.files || req.files.length === 0) {
    return res.status(400).json({ message: 'Please upload files' });
  }

  try {
    // Upload files to S3 (memory buffers)
    const { uploadMultipleFromMemory } = await import('../utils/s3Service.js');
    const uploadedFiles = await uploadMultipleFromMemory(req.files, 'work-updates');

    // Return the uploaded file URLs
    res.json({
      success: true,
      data: uploadedFiles,
      message: 'Files uploaded successfully to S3'
    });
  } catch (error) {
    console.error('S3 upload error:', error);
    res.status(500).json({ 
      success: false, 
      message: 'Failed to upload files to S3',
      error: error.message 
    });
  }
});

// @desc    Apply for leave
// @route   POST /api/employees/leave-request
// @access  Private (Employee)
export const applyMyLeave = asyncHandler(async (req, res) => {
  const { leaveType, startDate, endDate, reason } = req.body;
  
  const employee = await Employee.findOne({ userId: req.user._id });
  if (!employee) {
    return res.status(404).json({ message: 'Employee record not found' });
  }

  // Calculate number of days
  const start = new Date(startDate);
  const end = new Date(endDate);
  const days = Math.ceil((end - start) / (1000 * 60 * 60 * 24)) + 1;

  employee.leaves.push({
    leaveType,
    startDate,
    endDate,
    numberOfDays: days,
    reason,
    status: 'pending',
    appliedDate: new Date()
  });

  await employee.save();

  res.json({
    success: true,
    message: 'Leave request submitted successfully'
  });
});

// @desc    Get my leave requests
// @route   GET /api/employees/my-leaves
// @access  Private (Employee)
export const getMyLeaves = asyncHandler(async (req, res) => {
  const employee = await Employee.findOne({ userId: req.user._id })
    .populate('leaves.approvedBy', 'name');

  if (!employee) {
    return res.status(404).json({ message: 'Employee record not found' });
  }

  res.json({
    success: true,
    data: employee.leaves.sort((a, b) => b.appliedDate - a.appliedDate)
  });
});

// @desc    Get my calendar reminders
// @route   GET /api/employees/my-reminders
// @access  Private (Employee)
export const getMyReminders = asyncHandler(async (req, res) => {
  const { type, status } = req.query;

  let query = {
    $or: [
      { assignedTo: req.user._id },
      { createdBy: req.user._id }
    ]
  };

  if (type) query.type = type;
  if (status) query.status = status;

  const reminders = await CalendarReminder.find(query)
    .populate('assignedTo', 'name')
    .populate('completedBy', 'name')
    .sort({ date: 1 });

  res.json({
    success: true,
    data: reminders
  });
});

// @desc    Create calendar reminder
// @route   POST /api/employees/reminder
// @access  Private (Employee)
export const createReminder = asyncHandler(async (req, res) => {
  const reminder = await CalendarReminder.create({
    ...req.body,
    createdBy: req.user._id
  });

  res.status(201).json({
    success: true,
    data: reminder
  });
});

// @desc    Update reminder status
// @route   PUT /api/employees/reminder/:id
// @access  Private (Employee)
export const updateReminder = asyncHandler(async (req, res) => {
  const reminder = await CalendarReminder.findById(req.params.id);
  
  if (!reminder) {
    return res.status(404).json({ message: 'Reminder not found' });
  }

  // Check if user is the creator or assignee of the reminder
  const isCreator = reminder.createdBy.toString() === req.user._id.toString();
  const isAssignee = reminder.assignedTo.some(id => id.toString() === req.user._id.toString());
  
  if (!isCreator && !isAssignee) {
    return res.status(403).json({ message: 'Access denied. You can only modify your own reminders.' });
  }

  if (req.body.status === 'completed') {
    reminder.completedBy = req.user._id;
    reminder.completedDate = new Date();
  }

  reminder.status = req.body.status || reminder.status;
  await reminder.save();

  res.json({
    success: true,
    data: reminder
  });
});

// @desc    Reset all calendar reminders (Delete all)
// @route   DELETE /api/employees/reminders/reset
// @access  Private (Admin only)
export const resetAllReminders = asyncHandler(async (req, res) => {
  // Check if user has admin permissions
  if (req.user.role !== 'admin' && req.user.role !== 'main-admin') {
    return res.status(403).json({ message: 'Access denied. Admin rights required.' });
  }

  // Delete all calendar reminders
  const result = await CalendarReminder.deleteMany({});
  
  res.json({
    success: true,
    message: `Successfully deleted ${result.deletedCount} calendar reminders`,
    deletedCount: result.deletedCount
  });
});

// @desc    Reset my calendar reminders (Delete only user's reminders)
// @route   DELETE /api/employees/my-reminders/reset
// @access  Private (Employee)
export const resetMyReminders = asyncHandler(async (req, res) => {
  // Delete only reminders created by or assigned to the current user
  const result = await CalendarReminder.deleteMany({
    $or: [
      { createdBy: req.user._id },
      { assignedTo: req.user._id }
    ]
  });
  
  res.json({
    success: true,
    message: `Successfully deleted ${result.deletedCount} of your calendar reminders`,
    deletedCount: result.deletedCount
  });
});

// ============= HOLD REQUESTS (ADMIN) ==================
// @desc    List hold requests (flattened) with optional status filter
// @route   GET /api/employees/hold-requests
// @access  Private (Admin/accounts)
export const listHoldRequests = asyncHandler(async (req, res) => {
  const { status } = req.query;
  const employees = await Employee.find({}).select('name employeeId holdRequests holdBalance');
  const all = [];
  employees.forEach(emp => {
    (emp.holdRequests || []).forEach(r => {
      if (!status || r.status === status) {
        all.push({
          _id: r._id,
          employeeId: emp._id,
          employeeName: emp.name,
          empCode: emp.employeeId,
          amount: r.amount,
          status: r.status,
          requestedAt: r.requestedAt,
          processedAt: r.processedAt,
          notes: r.notes,
          holdBalanceAtFetch: emp.holdBalance || 0
        });
      }
    });
  });
  // Latest first
  all.sort((a, b) => new Date(b.requestedAt) - new Date(a.requestedAt));
  res.json({ success: true, data: all });
});

// @desc    Approve a hold withdrawal request
// @route   PUT /api/employees/hold-requests/:requestId/approve
// @access  Private (Admin/accounts)
export const approveHoldRequest = asyncHandler(async (req, res) => {
  const { requestId } = req.params;
  const { paymentMethod, referenceNumber, notes } = req.body;

  const employee = await Employee.findOne({ 'holdRequests._id': requestId });
  if (!employee) return res.status(404).json({ message: 'Request not found' });
  const request = employee.holdRequests.id(requestId);
  if (request.status !== 'pending') return res.status(400).json({ message: 'Request not pending' });
  const amount = request.amount || 0;
  if ((employee.holdBalance || 0) < amount) return res.status(400).json({ message: 'Insufficient hold balance' });

  // Deduct balance and mark approved
  employee.holdBalance = Math.max(0, (employee.holdBalance || 0) - amount);
  request.status = 'approved';
  request.processedAt = new Date();
  if (notes) request.notes = notes;
  await employee.save();

  // Notify employee
  if (employee.userId) {
    await createNotification({
      recipient: employee.userId,
      type: 'withdrawal_approved',
      title: 'Withdrawal Request Approved',
      message: `Your withdrawal request of ₹${amount.toLocaleString()} has been approved and will be processed soon`,
      actionUrl: '/my-salary',
      priority: 'high',
      triggeredBy: req.user._id
    });
  }

  // For now, record meta in response (Payment creation can be wired later if needed)
  res.json({ success: true, message: 'Withdrawal approved', data: { employeeId: employee._id, amount, paymentMethod, referenceNumber, holdBalance: employee.holdBalance } });
});

// @desc    Reject a hold withdrawal request
// @route   PUT /api/employees/hold-requests/:requestId/reject
// @access  Private (Admin/accounts)
export const rejectHoldRequest = asyncHandler(async (req, res) => {
  const { requestId } = req.params;
  const { notes } = req.body;
  const employee = await Employee.findOne({ 'holdRequests._id': requestId });
  if (!employee) return res.status(404).json({ message: 'Request not found' });
  const request = employee.holdRequests.id(requestId);
  if (request.status !== 'pending') return res.status(400).json({ message: 'Request not pending' });
  request.status = 'rejected';
  request.processedAt = new Date();
  if (notes) request.notes = notes;
  await employee.save();

  // Notify employee
  if (employee.userId) {
    await createNotification({
      recipient: employee.userId,
      type: 'withdrawal_rejected',
      title: 'Withdrawal Request Rejected',
      message: `Your withdrawal request of ₹${request.amount.toLocaleString()} was rejected${notes ? ': ' + notes : ''}`,
      actionUrl: '/my-salary',
      priority: 'high',
      triggeredBy: req.user._id
    });
  }

  res.json({ success: true, message: 'Withdrawal rejected' });
});

// @desc    Get human-readable address from coordinates
// @route   GET /api/employees/geocode
// @access  Private
export const geocodeLocation = asyncHandler(async (req, res) => {
  // Prevent caching
  res.set('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate');
  res.set('Pragma', 'no-cache');
  res.set('Expires', '0');
  
  const { lat, lon } = req.query;
  
  if (!lat || !lon) {
    return res.status(400).json({ message: 'Latitude and longitude are required' });
  }

  try {
    // Use OpenStreetMap Nominatim API for reverse geocoding
    const response = await fetch(
      `https://nominatim.openstreetmap.org/reverse?format=json&lat=${lat}&lon=${lon}&zoom=18&addressdetails=1`,
      {
        headers: {
          'User-Agent': 'SanjanaCRM/1.0 (contact@sanjanacrm.com)'
        }
      }
    );
    
    if (response.ok) {
      const data = await response.json();
      if (data && data.display_name) {
        // Extract meaningful parts of the address
        const parts = data.display_name.split(', ');
        // Take the first 3 parts for a concise address
        const address = parts.slice(0, 3).join(', ');
        
        return res.json({
          success: true,
          data: {
            address: address,
            fullAddress: data.display_name,
            coordinates: [parseFloat(lon), parseFloat(lat)]
          }
        });
      }
    }
    
    // Fallback to coordinates if geocoding fails
    res.json({
      success: true,
      data: {
        address: `${parseFloat(lat).toFixed(4)}, ${parseFloat(lon).toFixed(4)}`,
        coordinates: [parseFloat(lon), parseFloat(lat)]
      }
    });
  } catch (error) {
    console.error('Geocoding error:', error);
    // Fallback to coordinates if geocoding fails
    res.json({
      success: true,
      data: {
        address: `${parseFloat(lat).toFixed(4)}, ${parseFloat(lon).toFixed(4)}`,
        coordinates: [parseFloat(lon), parseFloat(lat)]
      }
    });
  }
});


// @desc    Generate my payslip PDF (Employee Self-Service)
// @route   GET /api/employees/my-payslip/:month
// @access  Private (Employee)
export const generateMyPayslip = asyncHandler(async (req, res) => {
  const { month } = req.params;
  
  try {
    // Find employee by userId
    const employee = await Employee.findOne({ userId: req.user._id })
      .populate('userId', 'name');
    
    if (!employee) {
      return res.status(404).json({ message: 'Employee record not found' });
    }
    
    // Find salary record for the specified month
    const salaryRecord = employee.salaryHistory.find(s => s.month === month);
    
    if (!salaryRecord) {
      return res.status(404).json({ message: `No salary record found for ${month}` });
    }
    
    // Prepare payslip data
    const payslipData = {
      employeeId: employee.employeeId,
      employeeName: employee.userId?.name || employee.name,
      department: employee.department,
      designation: employee.designation,
      month: salaryRecord.month,
      paymentDate: salaryRecord.paidDate,
      basicSalary: salaryRecord.basicSalary,
      allowances: employee.allowances,
      deductions: employee.deductions,
      totalDeductions: salaryRecord.totalDeductions,
      grossAmount: salaryRecord.basicSalary + salaryRecord.totalAllowances,
      netAmount: salaryRecord.netSalary
    };
    
    // Get company details from settings
    const Settings = (await import('../models/Settings.js')).default;
    const settings = await Settings.findOne();
    
    const companyDetails = {
      name: settings?.companyName || 'Sanjana Enterprises',
      address: settings?.companyAddress || '',
      phone: settings?.companyPhone || '',
      email: settings?.companyEmail || ''
    };
    
    // Prepare salary data for payslip
    const salaryData = {
      month: salaryRecord.month,
      paymentDate: salaryRecord.paidDate,
      paymentMode: salaryRecord.paymentMode || 'Bank Transfer',
      workingDays: salaryRecord.presentDays || 0,
      basicSalary: salaryRecord.basicSalary || employee.basicSalary || 0,
      hra: employee.allowances?.hra || 0,
      conveyance: employee.allowances?.conveyance || 0,
      medical: employee.allowances?.medical || 0,
      otherAllowances: employee.allowances?.other || 0,
      pf: employee.deductions?.pf || 0,
      esi: employee.deductions?.esi || 0,
      professionalTax: employee.deductions?.professionalTax || 0,
      tds: employee.deductions?.tds || 0,
      otherDeductions: salaryRecord.otherDeductions || 0,
      advance: salaryRecord.advanceDeduction || 0
    };
    
    // Generate PDF
    const generatePayslipPDF = (await import('../utils/payslipService.js')).default;
    const pdfBuffer = await generatePayslipPDF(salaryData, employee, companyDetails);
    
    // Set response headers
    const filename = `Payslip_${employee.employeeId}_${salaryRecord.month.replace('-', '_')}.pdf`;
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.setHeader('Content-Length', pdfBuffer.length);
    
    res.send(pdfBuffer);
  } catch (error) {
    console.error('Payslip generation error:', error);
    res.status(500).json({ message: 'Failed to generate payslip' });
  }
});

// @desc    Add employee document
// @route   POST /api/employee/employees/:id/documents
// @access  Private (Admin)
export const addEmployeeDocument = asyncHandler(async (req, res) => {
  const { name, type, url, fileSize, mimeType, expiryDate, notes } = req.body;

  const employee = await Employee.findById(req.params.id);
  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  employee.documents.push({
    name,
    type,
    url,
    fileSize,
    mimeType,
    uploadDate: new Date(),
    expiryDate: expiryDate || null,
    uploadedBy: req.user._id,
    notes,
    isVerified: false
  });

  await employee.save();

  res.status(201).json({
    success: true,
    message: 'Document added successfully',
    data: employee.documents[employee.documents.length - 1]
  });
});

// @desc    Delete employee document
// @route   DELETE /api/employee/employees/:id/documents/:documentId
// @access  Private (Admin)
export const deleteEmployeeDocument = asyncHandler(async (req, res) => {
  const employee = await Employee.findById(req.params.id);
  if (!employee) {
    return res.status(404).json({ message: 'Employee not found' });
  }

  const documentIndex = employee.documents.findIndex(
    doc => doc._id.toString() === req.params.documentId
  );

  if (documentIndex === -1) {
    return res.status(404).json({ message: 'Document not found' });
  }

  employee.documents.splice(documentIndex, 1);
  await employee.save();

  res.json({
    success: true,
    message: 'Document deleted successfully'
  });
});
